version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tifunbox-postgres
    restart: always
    environment:
      POSTGRES_DB: tifunbox_db
      POSTGRES_USER: tifunbox
      POSTGRES_PASSWORD: tifunbox
    ports:
      - "5432:5432"
    volumes:
      - tifunbox_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: tifunbox-backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://tifunbox:tifunbox@db:5432/tifunbox_db
      PORT: 3000
    ports:
      - "3000:3000"
      - "5555:5555"   # ðŸ‘ˆ ADD THIS
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  tifunbox_pgdata:
